server:
  port: 8099
  servlet:
    context-path: /

spring:
  application:
    name: lms-backend
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  profiles:
    active: dev

  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
    serialization:
      write-dates-as-timestamps: false

logging:
  level:
    com.bank.lms: debug
    org.springframework: info

lms:
  file:
    upload-path: ./upload
    max-size: 10MB
    allowed-types:
      audio:
        - mp3
        - wav
        - aac
      image:
        - jpg
        - jpeg
        - png
        - gif
        - pdf
      document:
        - pdf
        - doc
        - docx
        - txt
        - zip
        - rar
        - 7z
      video:
        - mp4
        - avi
        - mov
      archive:
        - zip
        - rar
        - 7z
        - tar
        - gz
  sms:
    enabled: false
