CREATE TABLE lms.loan_account (
    loan_account VARCHAR(32) PRIMARY KEY,
    customer_id VARCHAR(32) NOT NULL,
    customer_name VARCHAR(100),
    org_name VARCHAR(200),
    phone VARCHAR(20),
    product_code VARCHAR(32),
    product_name VARCHAR(100),
    loan_date DATE,
    loan_term INTEGER,
    overdue_days INTEGER DEFAULT 0,
    contract_amount DECIMAL(18,2),
    loan_balance DECIMAL(18,2),
    unexpired_principal DECIMAL(18,2),
    overdue_principal DECIMAL(18,2),
    overdue_interest DECIMAL(18,2),
    overdue_penalty DECIMAL(18,2),
    total_overdue_amount DECIMAL(18,2),
    status VARCHAR(20) DEFAULT 'uncollected',
    expected_days INTEGER DEFAULT 0,
    status_update_time TIMESTAMP,
    gbase_sync_time TIMESTAMP,
    gbase_raw_data TEXT,
    extra_data TEXT,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    is_deleted SMALLINT DEFAULT 0
);

CREATE TABLE lms.collection_record (
    record_id VARCHAR(32) PRIMARY KEY,
    loan_account VARCHAR(32) NOT NULL,
    customer_id VARCHAR(32) NOT NULL,
    customer_name VARCHAR(100),
    target_type VARCHAR(20),
    target_name VARCHAR(100),
    actual_collection_time TIMESTAMP,
    method VARCHAR(20) NOT NULL,
    method_text VARCHAR(50),
    result VARCHAR(500),
    operator_id VARCHAR(32),
    operator_name VARCHAR(100),
    operate_time TIMESTAMP,
    remark VARCHAR(500),
    material_type VARCHAR(20),
    material_name VARCHAR(200),
    material_url VARCHAR(500),
    extra_data TEXT,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    is_deleted SMALLINT DEFAULT 0
);

CREATE TABLE lms.litigation (
    litigation_id VARCHAR(32) PRIMARY KEY,
    loan_account VARCHAR(32) NOT NULL,
    customer_id VARCHAR(32) NOT NULL,
    customer_name VARCHAR(100),
    status_code VARCHAR(20) NOT NULL,
    status_text VARCHAR(200),
    in_litigation BOOLEAN DEFAULT FALSE,
    submit_to_law_firm_date VARCHAR(20),
    submit_to_court_date VARCHAR(20),
    filing_case_no VARCHAR(100),
    is_hearing BOOLEAN DEFAULT FALSE,
    hearing_date VARCHAR(20),
    judgment_date VARCHAR(20),
    execution_apply_to_court_date VARCHAR(20),
    execution_filing_date VARCHAR(20),
    execution_case_no VARCHAR(100),
    auction_status VARCHAR(50),
    litigation_fee DECIMAL(18,2) DEFAULT 0,
    litigation_fee_paid_by_customer BOOLEAN DEFAULT FALSE,
    preservation_fee DECIMAL(18,2) DEFAULT 0,
    preservation_fee_paid_by_customer BOOLEAN DEFAULT FALSE,
    appraisal_fee DECIMAL(18,2) DEFAULT 0,
    litigation_preservation_paid_at VARCHAR(20),
    litigation_preservation_write_off_at VARCHAR(20),
    lawyer_fee DECIMAL(18,2) DEFAULT 0,
    lawyer_fee_paid_by_customer BOOLEAN DEFAULT FALSE,
    court_name VARCHAR(200),
    law_firm VARCHAR(200),
    remark VARCHAR(500),
    extra_data TEXT,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    is_deleted SMALLINT DEFAULT 0
);

CREATE TABLE lms.notice (
    notice_id VARCHAR(32) PRIMARY KEY,
    title VARCHAR(200) NOT NULL,
    level VARCHAR(20),
    message VARCHAR(1000),
    customer_id VARCHAR(32),
    loan_account VARCHAR(32),
    customer_name VARCHAR(100),
    product_code VARCHAR(32),
    notice_type VARCHAR(50),
    overdue_days INTEGER,
    is_read BOOLEAN DEFAULT FALSE,
    extra_data TEXT,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    is_deleted SMALLINT DEFAULT 0
);
